// Regenerates public/sitemap.xml from the site routes and the extracted blog articles.
//   node scripts/extract-content.mjs && node scripts/build-sitemap.mjs
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..')
const articles = JSON.parse(fs.readFileSync(path.join(root, 'lib', 'content', 'articles.json'), 'utf8'))
const today = new Date().toISOString().replace(/\.\d+Z$/, 'Z')

const pages = [
  ['/', 1.0, 'weekly'],
  ['/photo-book/', 0.9, 'weekly'],
  ['/photobook/', 0.8, 'monthly'],
  ['/pricing/', 0.8, 'monthly'],
  ['/how-it-works/', 0.8, 'monthly'],
  ['/about-us/', 0.6, 'monthly'],
  ['/blog/', 0.8, 'weekly'],
  ['/blog/ideas/', 0.5, 'weekly'],
  ['/blog/how-to/', 0.5, 'weekly'],
  ['/faq/', 0.7, 'monthly'],
  ['/help-center/', 0.6, 'monthly'],
  ['/contact-us/', 0.5, 'yearly'],
  ['/shipping-info/', 0.5, 'monthly'],
  ['/track-order/', 0.3, 'yearly'],
  ['/privacy-policy/', 0.3, 'yearly'],
  ['/terms/', 0.3, 'yearly'],
]

const url = (loc, lastmod, freq, prio) =>
  `  <url>\n    <loc>https://pixovo.com${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${freq}</changefreq>\n    <priority>${prio.toFixed(1)}</priority>\n  </url>\n`

const body =
  pages.map(([l, p, f]) => url(l, today, f, p)).join('\n') +
  '\n' +
  articles.map((a) => url(`/blog/${a.slug}/`, a.updatedAt ?? today, 'monthly', 0.7)).join('\n')

fs.writeFileSync(
  path.join(root, 'public', 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n\n${body}\n</urlset>\n`,
)
console.log(`sitemap: ${pages.length + articles.length} urls`)
